version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/:/var/log/nginx
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"

  php:
    image: php:7.3-fpm
    container_name: php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./web/:/var/www/html
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    volumes:
      - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
